import test from 'node:test'; import assert from 'node:assert/strict';
import { buildHouseQuickModel } from '../custom_components/jamesui/frontend/modules/widget.house-quick/model.js';
const config={buttons:[{id:'heat',type:'heating_zone',source_id:'wohnen'},{id:'lights',type:'lights'},{id:'ambient',type:'ambient_lights'},{id:'devices',type:'devices'},{id:'energy',type:'energy',source_id:'house',average_window_minutes:15,warning_threshold_w:3500,critical_threshold_w:5000}]};const heating={version:1,zones:[{id:'wohnen',name:'Wohnen',current_temperature_c:21.4,target_temperature_c:22,heating_demand:true,auto_regulation_enabled:true,availability:'available',reason:null}]};const lights={version:1,items:[],on_count:3,total_count:8,unavailable_count:0};const ambient={version:1,items:[],on_count:0,total_count:4,unavailable_count:0};const devices={version:1,items:[],active_count:2,update_count:1,warning_count:0,fault_count:0,unreachable_count:0};const energy=[{request_id:'energy',source_id:'house',source_name:'Haus gesamt',window_minutes:15,current_power_w:1840,average_power_w:2100,quality:'full',reason:null}];
test('builds buttons in exact config order with approved display copy',()=>{const m=buildHouseQuickModel({config,heating,lights,ambientLights:ambient,devices,energyResults:energy});assert.deepEqual(m.map(x=>x.id),['heat','lights','ambient','devices','energy']);assert.equal(m[0].label,'Wohnen');assert.equal(m[0].primary,'21,4 → 22,0 °C');assert.equal(m[0].secondary,'Heizanforderung');assert.equal(m[1].primary,'3 von 8 an');assert.equal(m[2].primary,'0 von 4 an');assert.equal(m[3].primary,'2 aktiv');assert.match(m[3].secondary,/1 Update/);assert.equal(m[4].primary,'1,84 kW');assert.equal(m[4].secondary,'Ø 15 min: 2,1 kW');});
test('heating activity follows automation and not heat demand',()=>{const zones={version:1,zones:[{...heating.zones[0],auto_regulation_enabled:false,heating_demand:true}]};const m=buildHouseQuickModel({config:{buttons:[config.buttons[0]]},heating:zones});assert.equal(m[0].status,'neutral');assert.equal(m[0].secondary,'Heizanforderung');const active={version:1,zones:[{...zones.zones[0],auto_regulation_enabled:true,heating_demand:false}]};assert.equal(buildHouseQuickModel({config:{buttons:[config.buttons[0]]},heating:active})[0].status,'active');});
test('lighting warnings outrank active and ambient stays independent',()=>{const m=buildHouseQuickModel({config:{buttons:[config.buttons[1],config.buttons[2]]},lights:{...lights,unavailable_count:1},ambientLights:{...ambient,on_count:2}});assert.equal(m[0].status,'warning');assert.match(m[0].secondary,/1 nicht erreichbar/);assert.equal(m[1].status,'active');});
test('device severity is critical then warning then active and updates alone are informational',()=>{const button={buttons:[config.buttons[3]]};assert.equal(buildHouseQuickModel({config:button,devices:{...devices,active_count:1,update_count:2}})[0].status,'active');assert.equal(buildHouseQuickModel({config:button,devices:{...devices,active_count:1,warning_count:1}})[0].status,'warning');assert.equal(buildHouseQuickModel({config:button,devices:{...devices,active_count:1,warning_count:1,fault_count:1}})[0].status,'critical');assert.equal(buildHouseQuickModel({config:button,devices:{...devices,active_count:0,update_count:2}})[0].status,'neutral');});
test('energy uses average thresholds and warns when quality is insufficient',()=>{const button={buttons:[config.buttons[4]]};const result=(average,quality='full')=>[{...energy[0],average_power_w:average,quality}];assert.equal(buildHouseQuickModel({config:button,energyResults:result(3499)})[0].status,'neutral');assert.equal(buildHouseQuickModel({config:button,energyResults:result(3500)})[0].status,'warning');assert.equal(buildHouseQuickModel({config:button,energyResults:result(5000)})[0].status,'critical');assert.equal(buildHouseQuickModel({config:button,energyResults:result(null,'insufficient')})[0].status,'warning');});
test('unavailable or missing sources remain visible as warning buttons',()=>{const m=buildHouseQuickModel({config:{buttons:[{id:'missing',type:'heating_zone',source_id:'missing'},{id:'e',type:'energy',source_id:'missing',average_window_minutes:5,warning_threshold_w:100,critical_threshold_w:200}]},heating,energyResults:[]});assert.equal(m.length,2);assert.equal(m[0].status,'warning');assert.equal(m[0].primary,'Nicht verfügbar');assert.equal(m[1].status,'warning');});
