import test from 'node:test'; import assert from 'node:assert/strict';
import { createHouseDevicesProvider } from '../custom_components/jamesui/frontend/modules/provider.house-devices/provider.js';
const s=(id,value)=>({entity_id:id,state:value,attributes:{}}); const device=(id='washer')=>({id,name:id,primary_entity_id:`sensor.${id}_status`,active:{entity_id:`binary_sensor.${id}_active`},update_available:{entity_id:`update.${id}`},warning:{entity_id:`binary_sensor.${id}_warning`},fault:{entity_id:`binary_sensor.${id}_fault`}});
function env(initial={},connection='connected'){let conn=connection;const states=new Map(Object.entries(initial)),listeners=new Map(),connLs=new Set(),pub=[];let unreg=0;const context={homeAssistant:{connectionState:()=>conn,getState:id=>conn==='connected'?(states.get(id)??null):null,subscribeEntity(id,fn){if(!listeners.has(id))listeners.set(id,new Set());listeners.get(id).add(fn);return()=>{const set=listeners.get(id);set?.delete(fn);if(set?.size===0)listeners.delete(id);};},subscribeConnection(fn){connLs.add(fn);return()=>connLs.delete(fn);}},capabilities:{register(moduleId,cap){assert.equal(moduleId,'provider.house-devices');assert.equal(cap,'house.devices');return{available:v=>pub.push({status:'available',value:v}),unavailable:r=>pub.push({status:'unavailable',reason:r}),notConfigured:r=>pub.push({status:'not_configured',reason:r}),unregister(){unreg++;}};}}};return{context,pub,listeners,unreg:()=>unreg,setState(id,v){states.set(id,v);for(const fn of listeners.get(id)??[])fn(v);},setConn(v){conn=v;for(const fn of connLs)fn(v);}};}
function healthy(id='washer'){return{[`sensor.${id}_status`]:s(`sensor.${id}_status`,'idle'),[`binary_sensor.${id}_active`]:s(`binary_sensor.${id}_active`,'on'),[`update.${id}`]:s(`update.${id}`,'on'),[`binary_sensor.${id}_warning`]:s(`binary_sensor.${id}_warning`,'off'),[`binary_sensor.${id}_fault`]:s(`binary_sensor.${id}_fault`,'off')}}
test('zero devices is not configured',()=>{const e=env();createHouseDevicesProvider(e.context,{devices:[]}).mount();assert.equal(e.pub.at(-1).status,'not_configured');});
test('normalizes active update warning fault and aggregate counts',()=>{const states={...healthy('washer'),...healthy('dryer')};states['binary_sensor.dryer_active']=s('binary_sensor.dryer_active','off');states['update.dryer']=s('update.dryer','off');states['binary_sensor.dryer_warning']=s('binary_sensor.dryer_warning','on');const e=env(states);createHouseDevicesProvider(e.context,{devices:[device('washer'),device('dryer')]}).mount();const v=e.pub.at(-1).value;assert.deepEqual({active:v.active_count,updates:v.update_count,warnings:v.warning_count,faults:v.fault_count,unreachable:v.unreachable_count},{active:1,updates:1,warnings:1,faults:0,unreachable:0});});
test('missing or unavailable primary is unreachable without blanking siblings',()=>{const states={...healthy('washer'),...healthy('dryer')};delete states['sensor.washer_status'];const e=env(states);createHouseDevicesProvider(e.context,{devices:[device('washer'),device('dryer')]}).mount();const v=e.pub.at(-1).value;assert.equal(v.items[0].reachable,false);assert.equal(v.items[0].active,null);assert.equal(v.items[1].reachable,true);assert.equal(v.unreachable_count,1);});
test('unsupported optional signals are null and fault can coexist with activity',()=>{const cfg={id:'washer',name:'Washer',primary_entity_id:'sensor.washer_status',active:{entity_id:'binary_sensor.washer_active'},fault:{entity_id:'binary_sensor.washer_fault'}};const states={'sensor.washer_status':s('sensor.washer_status','ok'),'binary_sensor.washer_active':s('binary_sensor.washer_active','on'),'binary_sensor.washer_fault':s('binary_sensor.washer_fault','on')};const e=env(states);createHouseDevicesProvider(e.context,{devices:[cfg]}).mount();const item=e.pub.at(-1).value.items[0];assert.equal(item.active,true);assert.equal(item.fault,true);assert.equal(item.update_available,null);assert.equal(item.warning,null);assert.equal(e.pub.at(-1).value.fault_count,1);});
test('duplicate physical sources subscribe once and updates publish',()=>{const cfg={id:'x',name:'X',primary_entity_id:'sensor.shared',active:{entity_id:'sensor.shared',true_values:['run'],false_values:['idle']}};const e=env({'sensor.shared':s('sensor.shared','run')});const p=createHouseDevicesProvider(e.context,{devices:[cfg]});p.mount();assert.equal(e.listeners.get('sensor.shared').size,1);e.setState('sensor.shared',s('sensor.shared','idle'));assert.equal(e.pub.at(-1).value.active_count,0);});
test('disconnect reconnect update destroy preserve lifecycle',()=>{const e=env({...healthy('washer'),...healthy('dryer')});const p=createHouseDevicesProvider(e.context,{devices:[device('washer')]});p.mount();e.setConn('disconnected');assert.equal(e.pub.at(-1).status,'unavailable');e.setConn('connected');assert.equal(e.pub.at(-1).status,'available');p.update(e.context,{devices:[device('dryer')]});assert.equal(e.pub.at(-1).value.items[0].id,'dryer');p.destroy();assert.equal(e.listeners.size,0);assert.equal(e.unreg(),1);});
