import test from 'node:test';
import assert from 'node:assert/strict';
import { createHouseLightingProvider } from '../custom_components/jamesui/frontend/modules/provider.house-lighting/provider.js';
const light=(id,entity_id)=>({id,name:id,state:{entity_id}}); const entity=(id,value)=>({entity_id:id,state:value,attributes:{}});
function env(statesInit={}, connection='connected'){ let conn=connection; const states=new Map(Object.entries(statesInit)); const listeners=new Map(); const connListeners=new Set(); const publications={}; let unregisters=0; const context={homeAssistant:{connectionState:()=>conn,getState:(id)=>conn==='connected'?(states.get(id)??null):null,subscribeEntity(id,fn){if(!listeners.has(id))listeners.set(id,new Set());listeners.get(id).add(fn);return()=>{const s=listeners.get(id);s?.delete(fn);if(s?.size===0)listeners.delete(id);};},subscribeConnection(fn){connListeners.add(fn);return()=>connListeners.delete(fn);},entities(){throw new Error('discovery forbidden');}},capabilities:{register(moduleId,cap){assert.equal(moduleId,'provider.house-lighting');publications[cap]=[];return{available(value){publications[cap].push({status:'available',value});},unavailable(reason){publications[cap].push({status:'unavailable',reason});},notConfigured(reason){publications[cap].push({status:'not_configured',reason});},unregister(){unregisters++;}};}}}; return{context,publications,listeners,unregisters:()=>unregisters,setState(id,s){states.set(id,s);for(const fn of listeners.get(id)??[])fn(s);},setConn(v){conn=v;for(const fn of connListeners)fn(v);}}; }
test('publishes independent not configured and configured capabilities',()=>{const e=env({'light.a':entity('light.a','on')});createHouseLightingProvider(e.context,{lights:[light('A','light.a')],ambient_lights:[]}).mount();assert.equal(e.publications['house.lights'].at(-1).status,'available');assert.equal(e.publications['house.ambientLights'].at(-1).status,'not_configured');});
test('counts configured, on and unavailable lights truthfully',()=>{const states={};for(let i=1;i<=8;i++)states[`light.${i}`]=entity(`light.${i}`,i<=3?'on':'off');states['light.8']=entity('light.8','unavailable');const e=env(states);const lights=Array.from({length:8},(_,i)=>light(`L${i+1}`,`light.${i+1}`));createHouseLightingProvider(e.context,{lights,ambient_lights:[]}).mount();const value=e.publications['house.lights'].at(-1).value;assert.equal(value.total_count,8);assert.equal(value.on_count,3);assert.equal(value.unavailable_count,1);assert.equal(value.items[7].availability,'unavailable');});
test('failed source does not hide healthy siblings and updates live',()=>{const e=env({'light.a':entity('light.a','on'),'light.b':entity('light.b','unknown')});createHouseLightingProvider(e.context,{lights:[light('A','light.a'),light('B','light.b')],ambient_lights:[]}).mount();let value=e.publications['house.lights'].at(-1).value;assert.equal(value.items[0].on,true);assert.equal(value.items[1].on,null);assert.equal(value.unavailable_count,1);e.setState('light.b',entity('light.b','on'));value=e.publications['house.lights'].at(-1).value;assert.equal(value.on_count,2);assert.equal(value.unavailable_count,0);});
test('subscribes explicit physical sources once and never discovers domain',()=>{const e=env({'light.a':entity('light.a','off'),'light.b':entity('light.b','off')});createHouseLightingProvider(e.context,{lights:[light('A','light.a')],ambient_lights:[light('B','light.b')]}).mount();assert.equal(e.listeners.size,2);assert.equal(e.listeners.get('light.a').size,1);});
test('disconnect, reconnect, update and destroy preserve lifecycle',()=>{const e=env({'light.a':entity('light.a','on'),'light.b':entity('light.b','off')});const p=createHouseLightingProvider(e.context,{lights:[light('A','light.a')],ambient_lights:[]});p.mount();e.setConn('disconnected');assert.equal(e.publications['house.lights'].at(-1).status,'unavailable');e.setConn('connected');assert.equal(e.publications['house.lights'].at(-1).status,'available');p.update(e.context,{lights:[],ambient_lights:[light('B','light.b')]});assert.equal(e.publications['house.lights'].at(-1).status,'not_configured');assert.equal(e.publications['house.ambientLights'].at(-1).value.total_count,1);assert.equal(p.destroy(),true);assert.equal(e.listeners.size,0);assert.equal(e.unregisters(),2);assert.equal(p.destroy(),false);});
