const DEFAULT_ICONS=Object.freeze({heating_zone:"home.climate",lights:"home.light",ambient_lights:"home.light",devices:"home.device",energy:"home.energy"});
const nfPowerKw=new Intl.NumberFormat("de-DE",{maximumFractionDigits:2});const nfPowerW=new Intl.NumberFormat("de-DE",{maximumFractionDigits:0});const nfTemp=new Intl.NumberFormat("de-DE",{minimumFractionDigits:1,maximumFractionDigits:1});
function formatPower(value){if(!Number.isFinite(value))return"Nicht verfügbar";if(Math.abs(value)>=1000)return`${nfPowerKw.format(value/1000)} kW`;return`${nfPowerW.format(value)} W`;}
function warningFallback(button,label){return Object.freeze({id:button.id,type:button.type,label,primary:"Nicht verfügbar",secondary:null,status:"warning",icon:button.icon??DEFAULT_ICONS[button.type],navigation:button.navigation??null});}
function base(button,label,primary,secondary,status){return Object.freeze({id:button.id,type:button.type,label,primary,secondary,status,icon:button.icon??DEFAULT_ICONS[button.type],navigation:button.navigation??null});}
function heatingModel(button,heating){const zone=heating?.zones?.find((item)=>item.id===button.source_id);if(!zone)return warningFallback(button,button.source_id);const temps=Number.isFinite(zone.current_temperature_c)&&Number.isFinite(zone.target_temperature_c)?`${nfTemp.format(zone.current_temperature_c)} → ${nfTemp.format(zone.target_temperature_c)} °C`:"Nicht verfügbar";const secondary=zone.heating_demand===true?"Heizanforderung":zone.heating_demand===false?"Keine Heizanforderung":"Heizanforderung unbekannt";const status=zone.availability!=="available"?"warning":zone.auto_regulation_enabled===true?"active":"neutral";return base(button,zone.name,temps,secondary,status);}
function lightModel(button,value,label){if(!value)return warningFallback(button,label);const primary=`${value.on_count} von ${value.total_count} an`;const secondary=value.unavailable_count>0?`${value.unavailable_count} nicht erreichbar`:null;const status=value.unavailable_count>0?"warning":value.on_count>0?"active":"neutral";return base(button,label,primary,secondary,status);}
function plural(count,singular,pluralValue){return`${count} ${count===1?singular:pluralValue}`;}
function deviceModel(button,devices){if(!devices)return warningFallback(button,"Geräte");const details=[];if(devices.update_count>0)details.push(plural(devices.update_count,"Update","Updates"));if(devices.warning_count>0)details.push(plural(devices.warning_count,"Warnung","Warnungen"));if(devices.fault_count>0)details.push(plural(devices.fault_count,"Störung","Störungen"));if(devices.unreachable_count>0)details.push(`${devices.unreachable_count} nicht erreichbar`);const status=devices.fault_count>0?"critical":(devices.warning_count>0||devices.unreachable_count>0)?"warning":devices.active_count>0?"active":"neutral";return base(button,"Geräte",`${devices.active_count} aktiv`,details.length?details.join(" · "):null,status);}
function energyModel(button,energyByRequest){const result=energyByRequest.get(button.id);if(!result)return warningFallback(button,button.source_id);const label=result.source_name??button.source_id;const primary=formatPower(result.current_power_w);const secondary=`Ø ${button.average_window_minutes} min: ${formatPower(result.average_power_w)}`;let status="warning";if(result.quality==="full"&&Number.isFinite(result.average_power_w)){status=result.average_power_w>=button.critical_threshold_w?"critical":result.average_power_w>=button.warning_threshold_w?"warning":"neutral";}return base(button,label,primary,secondary,status);}
export function buildHouseQuickModel({config,heating=null,lights=null,ambientLights=null,devices=null,energyResults=[]}={}){const byRequest=new Map((energyResults??[]).map((item)=>[item.request_id,item]));return Object.freeze((config?.buttons??[]).map((button)=>{switch(button.type){case"heating_zone":return heatingModel(button,heating);case"lights":return lightModel(button,lights,"Licht");case"ambient_lights":return lightModel(button,ambientLights,"Ambientelicht");case"devices":return deviceModel(button,devices);case"energy":return energyModel(button,byRequest);default:return warningFallback(button,button.type);}}));}
